version: "3"
services:
  web:
    build:
      context: .
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: sekret
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "4000:4000"
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: sekret
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
